/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

// This code is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 85hfiNoWr9NpnmarETBLiB

import { createUseGlobalVariants } from "@plasmicapp/react-web";

import { useScreenVariants as useScreenVariantsk9NA5UnvsOvn } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: k9nA5UnvsOVN/globalVariant

export const _useGlobalVariants = createUseGlobalVariants({
  screen: useScreenVariantsk9NA5UnvsOvn
});
